### ISSUE TITLE
 Unrecognized http-protocol header

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#1]
req_res_impl.hpp  line:190   触发 Unrecognized http-protocol header,请检查

**Comment by fawdlstty** [comment]
服务器端返回原始数据是怎样的

**Comment by sudavida** [comment]
这个问题可能导致后面接收到的数据是错的，我改后，快跑了一个半小时了，没出问题

**Comment by fawdlstty** [comment]
遇到无法解析的情况，取一下服务器返回的原始数据吧，我看看怎么改

**Comment by fawdlstty** [comment]
duplicate #5
