### ISSUE TITLE
domethod函数，取返回，这里，加个错误处理是不是更好，处理乱码解析错误

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#11]
try {
            Response _ret = co_await Response::GetFromConn(Conn);
        }catch(...){
            co_await Conn->Reconnect ();
		}

**Comment by sudavida** [comment]
有错误，断线重连

**Comment by sudavida** [comment]
出现乱码，说明数据流乱序了，错误会影响后面报文。这种情况最好连接重置

**Comment by fawdlstty** [comment]
这种改法有争议，且try catch及reconnect完全可以移到库外面去处理，因此暂时不变，调查一下上一个问题来再处理更好

**Comment by sudavida** [comment]
好
