### ISSUE TITLE
line:185要去掉，编译不过

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#13]
fv/session.hpp: In function 鈥�void fv::Session::Delete(fv::Session::Delete<>(std::string)::_ZN2fv7Session6DeleteIJEEEN4asio9awaitableINS_8ResponseENS2_15any_io_executorEEESs.frame*)鈥�:
/tmp/tmp.XDfMT4Ask1/bub/http/fv/session.hpp:187:78: internal compiler error: Segmentation fault
  187 |     co_return co_await DoMethod (Request { _url, MethodType::Delete });

**Comment by fawdlstty** [comment]
这段代码很长时间也没改过，可查看commit log。是不是你编译环境有调整

**Comment by sudavida** [comment]
没有，这个函数没有用到模板，gcc会报错
