### ISSUE TITLE
websocket client 发送数据格式需要重新检查

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#17]
发送订阅channel'数据，被服务器直接close，可能数据格式不对。

**Comment by fawdlstty** [comment]
具体客户端代码怎样？然后怎样的订阅不会被close？

**Comment by sudavida** [comment]
可以参考下，怀疑握手没有完成：
https://blog.csdn.net/qq_21539375/article/details/123632609
https://wenku.baidu.com/view/bb92d2577cd5360cba1aa8114431b90d6c85890b.html

**Comment by sudavida** [comment]
connecting...
tcp connected.
send ws handshake data:
GET /ws/v5/public HTTP/1.1
Host: ws.okx.com
Connection: Upgrade
Accept: */*
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36
Sec-WebSocket-Version: 13
Cache-Control: no-cache
Accept-Encoding: 
Pragma: no-cache
Sec-WebSocket-Protocol: chat
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==


handshake response:
no handshake data frow ws server. connect failed.
send subscribe data:{"op":"subscribe","args":[{"channel":"tickers","instId":"SC-USDT-SWAP"}]}
do while recv... 
Remote send close msg.

**Comment by sudavida** [comment]
流程大概这样，看下有没有问题

**Comment by fawdlstty** [comment]
开发阶段，作为ws服务器，能让浏览器连接，作为客户端，测成功连接其他服务。所以你不说清详细信息我也没法帮你看

**Comment by sudavida** [comment]
用在线工具检查服务器：http://coolaf.com/tool/chattest
测试用websocket服务器情况：
服务器： wss://ws.okx.com/ws/v5/public
连接后发送订阅数据：{"op":"subscribe","args":[{"channel":"tickers","instId":"SC-USDT-SWAP"}]}
服务器返回订阅成功：{"event":"subscribe","arg":{"channel":"tickers","instId":"SC-USDT-SWAP"}}

**Comment by sudavida** [comment]
现在客户端，连接情况：tcp连接应该可以，websocket连接阶段，发送握手数据到服务器，没有返回

**Comment by sudavida** [comment]
ConnectWS（）{
。。。
		Request _r { _url, MethodType::Get };
		_r.Headers ["Pragma"] = "no-cache";
        _r.Headers ["Connection"] = "Upgrade";
        _r.Headers ["Upgrade"] = "websocket";

         _r.Headers ["Sec-WebSocket-Version"] = "13"; // line414
		_r.Headers ["Sec-WebSocket_Key"] = "dGhlIHNhbXBsZSBub25jZQ==";
		std::string _data = _r.Serilize (_host, _path);
。。。
}

line:414, 发生错误: not a WebSocket request: missing key
注销后，发生错误：Missing origin header, got only [Host, X-Real-IP, X-Forwarded-Proto, Upgrade, Connection, X-Request-ID, Pragma, User-Agent, Accept, Accept-Encoding, Cache-Control, content-length]

**Comment by sudavida** [comment]
握手有反应了，但是报错

**Comment by sudavida** [comment]
这个函数可能有错，sendtext数据出去，出现400 bad request错误

**Comment by sudavida** [comment]
握手连接测试成功。前面看没有应当原因是，返回数据只有header，没有body。现在要测试数据打包格式是不是对的，发过去数据会导致连接断开wsType::Close

**Comment by sudavida** [comment]
服务器返回：received a frame that is not masked as expected
请检查代码有没有设置第二个字节第一个bit掩码标志位
