### ISSUE TITLE
这里是否要unlock，多次连不上服务器是否会导致后续协程堆积？

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#22]
for (size_t i = 0; i < 2; i++) {
				try {
					// send
					co_await Conn->Send (_data.data (), _data.size ());
					break;
				} catch (...) {
					if (i == 1)
                        SessMtx.Unlock (); //这里是否要加上
					    throw;
				}
				co_await Conn->Reconnect ();

**Comment by fawdlstty** [comment]
这么写没问题
