### ISSUE TITLE
这段代码是不是放到session捕获具体的错误进行处理，如果throw到业务层，每个函数都要带着，不太好

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#25]
if (err.find("wrong version number",0)!=std::string::npos  || err.find("Operation aborted",0)!=std::string::npos || err.find("Broken pipe",0)!=std::string::npos || err.find("End of file",0)!=std::string::npos || err.find("shutdown: Transport endpoint is not connected",0)!=std::string::npos) 
其中Broken pipe，这个错误比较特别，reconnect（）解决不了，session要重置，conn.close; conn =nullptr; session.connFlag ="";
其他的reconnet（）就可以了

**Comment by fawdlstty** [comment]
duplicate #24
