### ISSUE TITLE
doMethod（）抛出异常

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#26]
```cpp
		try {
			auto [_schema, _host, _port, _path] = _parse_url (_r.Url);
			std::string _conn_flag = fmt::format ("{}://{}:{}", _schema, _host, _port);
			if (!Conn || ConnFlag != _conn_flag) {
				ConnFlag = _conn_flag;
				if (_schema == "https") {
					Conn = std::shared_ptr<IConn> (new SslConn {});
				} else {
					Conn = std::shared_ptr<IConn> (new TcpConn {});
				}
				auto _ip = co_await Config::DnsResolve (_host);
				co_await Conn->Connect (_ip != "" ? _ip : _host, _port);
			}

			_r.Schema = _schema;
			_r.UrlPath = _path;

			//// cancel
			//AsyncTimer _timer {};
			//if (std::chrono::duration_cast<std::chrono::nanoseconds> (_r.Timeout).count () > 0) {
			//	_timer.WaitCallback (_r.Timeout, [_tconn = std::weak_ptr (Conn)] ()->Task<void> {
			//		auto _conn = _tconn.lock ();
			//		if (_conn)
			//			_conn->Cancel ();
			//	});
			//}

			// generate data
			std::string _data = _r.Serilize (_host, _port, _path);

			for (size_t i = 0; i < 2; i++) {
				try {
					// send
					co_await Conn->Send (_data.data (), _data.size ());
					break;
				} catch (std::exception& e) {
                                        std::cout<<"doMethod1:"<<e.what()<<",i:"<<i<<"\n";
					if (i == 1)
						throw;
				}
				co_await Conn->Reconnect ();
			}

			SessMtx.Unlock ();
			_is_lock = false;

			// recv
			Response _ret = co_await Response::GetFromConn (Conn);
			//_timer.Cancel ();
			co_return _ret;
		} catch (std::exception& e) {
		    std::cout<<"doMethod2:"<<e.what()<<"\n";
			if (_is_lock)
				SessMtx.Unlock ();
			Conn = nullptr;
			throw;
		}
```

**Comment by sudavida** [comment]
这个代码我做了标记，
实际跑起来，是这样：
Message from producer 1: 4457
start1------------------:1654831048901
doMethod2:End of file

**Comment by sudavida** [comment]
感觉是co_await Conn->Send (_data.data (), _data.size ()); 出现异常，没有被for循环内的try 。。。catch捕获，直接到了最外层来处理。结果是跳过了reconnect（）执行。
不科学啊

**Comment by sudavida** [comment]
Task<Response> DoMethod (Request _r) {
                Response _ret;
		co_await SessMtx.Lock ();
		auto[_schema, _host, _port, _path] = _parse_url(_r.Url);
		try {

            std::string _conn_flag = fmt::format("{}://{}:{}", _schema, _host, _port);
            if (!Conn || ConnFlag != _conn_flag) {
                ConnFlag = _conn_flag;
                if (_schema == "https") {
                    Conn = std::shared_ptr<IConn>(new SslConn{});
                } else {
                    Conn = std::shared_ptr<IConn>(new TcpConn{});
                }
                auto _ip = co_await
                Config::DnsResolve(_host);
                co_await
                Conn->Connect(_ip != "" ? _ip : _host, _port);
            }

            _r.Schema = _schema;
            _r.UrlPath = _path;
        }catch(...) {

        }

        // generate data
        std::string _data = _r.Serilize (_host, _port, _path);
        for (size_t i = 0; i < 2; i++) {
            try {
                // send
                co_await Conn->Send (_data.data (), _data.size ());
                break;
            } catch (std::exception& e) {
                std::cout<<"doMethod1:"<<e.what()<<",i:"<<i<<"\n";
                if (i == 1) throw;
            }
            co_await Conn->Reconnect ();
        }

        try{
            //recv
			_ret = co_await Response::GetFromConn(Conn);

		} catch (std::exception& e) {
		    std::cout<<"doMethod2:"<<e.what()<<"\n";
            co_await Conn->Reconnect ();
            throw;
		}

        SessMtx .Unlock ();
		co_return _ret;
	}

**Comment by sudavida** [comment]
我改成这样跑跑试试，try catch 不嵌套

**Comment by fawdlstty** [comment]
源码里是 catch (...)，你应该是改出了问题

**Comment by sudavida** [comment]
我为了打标记，看看什么错误才改的

**Comment by sudavida** [comment]
按最新改的程序，跑了十几个小时，报错：


Message from producer 1: 4761
start2------------------:1654938070558
for send data  ok.... //RunAsync（）调用业务函数2，发送数据成功但无返回

Message from producer 1: 4761
start1------------------:1654938070682  //RunAsync（）调用业务函数1，被锁拦住，可能前面原因，不太清楚 ，没进入Session DoMethod();

Message from producer 2: 5  
for send data  ok....    // RunAsync（）调用业务函数2，显示Send（）成功 ，但是捕获错误：Operation aborted
doMethod catch error://这里触发Conn=nullptr；
get data error:Operation aborted.  
response------------------:1654938070791

Message from producer 2: 5
doMethod catch error:  //Conn可能哪个地方在用，然后遇到空指针，段错误程序退出
段错误

**Comment by sudavida** [comment]
1.这步已经产生问题：
Message from producer 1: 4761
start2------------------:1654938070558
for send data ok.... //RunAsync（）调用业务函数2，发送数据成功但无返回

2.这个地方是不是锁的问题，RunAsync（）需不需要加锁
Message from producer 1: 4761
start1------------------:1654938070682 //RunAsync（）调用业务函数1，被锁拦住，可能前面原因，不太清楚 ，没进入Session DoMethod();
3.抛出异常，重置Conn==nullptr后，报段错误，可能其他的协程在用Conn？

 Message from producer 2: 5
for send data ok.... // RunAsync（）调用业务函数2，显示Send（）成功 ，但是捕获错误：Operation aborted
doMethod catch error://这里触发Conn=nullptr；
get data error:Operation aborted.
response------------------:1654938070791

Message from producer 2: 5
doMethod catch error: //Conn可能哪个地方在用，然后遇到空指针，段错误程序退出
段错误

**Comment by sudavida** [comment]
感觉其他协程有可能已经同时进入Session doMethod（）

**Comment by fawdlstty** [comment]
session的锁为了避免同时请求从而导致的创建多个连接；conn的锁为了避免解析http协议过程中立即开始解析另一个http协议

**Comment by sudavida** [comment]
for (size_t i = 0; i < 2; i++) {
                try {
                    // send
                    co_await Conn->Send (_data.data (), _data.size ());
                    std::cout<<"for send data  ok...."<<"\n";
                    break;
                } catch (...) {   //这里捕获不了所有的错误，比如Operation Aborted，Broken pipe //前面Send是成功的，但是还是抛出错误，和协程的机制有关？
                    std::cout<<"for send data  error....,i:"<<i<<"\n";    
                    if (i == 1)
                        throw;
                }
                std::cout<<"for send data error, reconnect....,i:"<<i<<"\n";
                co_await Conn->Reconnect ();
            }

**Comment by sudavida** [comment]
比如：
Message from producer 2: 5
for send data ok....  //成功发送
doMethod catch error:   //在外层捕获错误 
get data error:Operation aborted. //继续抛到业务层
response------------------:1654938070791

**Comment by sudavida** [comment]
也许是这里抛出了异常：
 Response _ret = co_await Response::GetFromConn (Conn);

**Comment by sudavida** [comment]
catch (std::exception& e) {
            std::cout<<"doMethod catch error:"<<"\n";
            if (_is_lock)
                SessMtx.Unlock ();
                Conn->Reconnect(); //改了这里，再试
            throw;
        }

**Comment by sudavida** [comment]
改过后，跑了30个小时，没出错，继续跑，看看有没有问题

**Comment by sudavida** [comment]
这样改后应该没有问题了

**Comment by fawdlstty** [comment]
`Conn = nullptr;` 才能实现重连。如果单纯重连，调用 `Reconnect ()` 需带个`co_await`；但catch代码块里不允许`co_await`

**Comment by sudavida** [comment]
我catch{}加了 co_await  Conn->Reconnect(); 
没报错啊

**Comment by sudavida** [comment]
编译过去了

**Comment by fawdlstty** [comment]
```
D:\GitHub\_\libfv\include\fv\session.hpp(115): error C2304: 不能在 catch 块内使用“co_await”
```

**Comment by sudavida** [comment]
又编译了一次，还是过了

**Comment by sudavida** [comment]
doMethod catch error: 段错误
catch（）到错误，重连出现段错误，可能遇到空指针

**Comment by fawdlstty** [comment]
这个锁不是为了限制并行，而是为了使得同一个session的连接只由一次请求创建

**Comment by sudavida** [comment]
那就是说截获异常后，Conn被重置为nullptr， 但是别的请求可能还在用这个Conn，结果就段错误了。
怎么解决呢，弄了好久，这个地方

**Comment by fawdlstty** [comment]
我加个连接池吧

**Comment by sudavida** [comment]
好

**Comment by fawdlstty** [comment]
ref <https://github.com/fawdlstty/libfv/commit/fbef38e58cf12a79ac1bf0563afa6a1ecd71346f>

**Comment by sudavida** [comment]
还是会发生段错误，我打满了标记，准备捉bug
等我找出错误再改吧
还有个办法，实在不行把报出异常的Session，扔掉

**Comment by fawdlstty** [comment]
抛出异常的Session是会扔出线程池

**Comment by fawdlstty** [comment]
duplicate #29
