### ISSUE TITLE
接收数据触发异常，貌似读数据_size()超过了数据的实际长度。调用链Response::GetFromConn (Conn)；readline（）；RecvImpl （）

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#27]
inline Task<size_t> SslConn::RecvImpl (char *_data, size_t _size) {
    std::cout<<"12:"<<"\n";
	co_return co_await SslSocket->async_read_some (asio::buffer (_data, _size), UseAwaitable);
}

**Comment by sudavida** [comment]
不确定中间是readline（）还是ReadCount（）

**Comment by sudavida** [comment]
一：
这里会触发 End of file，表示已经读取完毕，但是会抛出异常，这个需要catch（），如果读的数据并没有错，可以截获，不处理；

二：doMethod（）这里Conn=nullptr；会触发段错误。我去掉，换成：if(Conn!=nullptr) Conn->Close();

**Comment by sudavida** [comment]
初步判断，段错误的原因可能有2：
1：throw出来的Exception，不全是std::exception类型，有没有拦截到的exception；
2：conn == nullptr；这句会导致socket异常，可能某个地方socket还在使用，和shutdown（）类似；
     经检验，conn->Close（）函数里，Sslsocket =nullptr；这句也同样会导致异常；

**Comment by sudavida** [comment]
已经改了在跑，1天半没有出错了，再跑2天没有问题就ok了

**Comment by sudavida** [comment]
用的是加异步锁的版本。没有用最后一次提交的代码。

**Comment by fawdlstty** [comment]
用最后的版本吧。异步锁版本性能相对来说比最后的版本低，且存在性能问题

**Comment by sudavida** [comment]
好

**Comment by shoushouzhuo2** [comment]
> 已经改了在跑，1天半没有出错了，再跑2天没有问题就ok了

我也遇到了这个问题，请问是怎么处理的 呢

**Comment by fawdlstty** [comment]
@shoushouzhuo2 使用git上最新版本还有这问题么？有的话开一个新的issue并贴出复现demo

**Comment by shoushouzhuo2** [comment]
> @shoushouzhuo2 使用git上最新版本还有这问题么？有的话开一个新的issue并贴出复现demo

对的，新版有，马上提交issue， 但你运行这demo估计得5-10分钟才能获得报错哟，我都复现了好几次了
