### ISSUE TITLE
Conn Close（）触发Bad file descriptor异常，导致程序崩溃，catch不住

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#29]
Conn->Close（）；
这里看Asio源码是一定会抛出异常的，我看也做了try..catch();
但是这个异常会触发程序崩溃。

asio：
  void close()
  {
    asio::error_code ec;
    impl_.get_service().close(impl_.get_implementation(), ec);
    asio::detail::throw_error(ec, "close");
  }
错误日志：
close socket.
terminate called after throwing an instance of 'std::system_error'
  what():  cancel: Bad file descriptor

**Comment by sudavida** [comment]
改成这样在试：

inline void SslConn::Close () {
    if (SslSocket && SslSocket->next_layer().is_open()) {

        asio::error_code ec;
        SslSocket->next_layer().shutdown(SocketBase::shutdown_both, ec);
        try {
            std::cout << "close socket." << "\n";
            SslSocket->next_layer().close();

        }catch(...){
            std::cout<<"close socket error."<<"\n";
        }

    }

}

**Comment by fawdlstty** [comment]
最新版的libfv已处理这个问题

**Comment by fawdlstty** [comment]
备注：catch (...)无法捕获的可能和系统环境相关。libfv暂时无法处理

**Comment by sudavida** [comment]
现在暂时放弃使用socket->Close（), 默认出异常底层会处理file discriptor，不会造成文件描述符不够的情况；
不主动close socket，目前看没有出啥问题，用一个测试跑了几天没有出问题

**Comment by fawdlstty** [comment]
如果问题确实与asio有关，建议你去给asio提issue

**Comment by sudavida** [comment]
https://github.com/boostorg/asio/issues/112，按这个解释，可能需要先cancel吧

**Comment by fawdlstty** [comment]
你那边测试效果怎样

**Comment by sudavida** [comment]
还没来得及测试，服务器跑着测试用例，等我测试完反馈

**Comment by sudavida** [comment]
现在跑着都是不用close（）的
session_pool()昨天晚上有个高峰，24个session出来了，到现在已经自己变成3个，可能是碰到问题，没放回去，自己剔除了

**Comment by sudavida** [comment]
conn->Close（）,加了cancel（）：
1.websocket（）连接close（）没有问题
receiver.h (450) websocket:Remote send close msg.
 
下面看看http方式Close（）有么有问题

**Comment by fawdlstty** [comment]
看起来不close的没问题。那就不close了，让socket的析构函数自己释放算了

**Comment by sudavida** [comment]
http方式至少要跑半天到一天，才能发现问题，不过人家建议socket close前先cancel

**Comment by sudavida** [comment]
cancel做了啥事，不清楚是不是把正常的session影响了，还要观察

**Comment by fawdlstty** [comment]
出异常的连接理论上已经断掉了，不需要再close一下。直接去除close我看行

**Comment by sudavida** [comment]
我看也是，不过我测试下，给个明确的结论，看看cancel效果是啥

**Comment by sudavida** [comment]
加上cancel（）解决不了问题，session doMethod（）只能把conn->close（）或者conn=nullptr之类的去掉了

**Comment by fawdlstty** [comment]
最新版本你那边用起来稳定了么
