### ISSUE TITLE
能不能增加重连的成功率

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#3]
一般dns解析会返回1个或多个IP地址，如果有多个IP地址，重连时，刚才断掉的IP地址，可以选择跳过

**Comment by sudavida** [comment]
还有个选项，能不能对连接有个时间上的timeout，时间间隔到了，即使没断，也可以重新连接

**Comment by fawdlstty** [comment]
dns缓存池主要受限于查询种类多，比如udp53、http(s)等，做这一块会一定程度上失去通用性。因此在想好比较完美的方案前，暂不计划加入

**Comment by fawdlstty** [comment]
已更新dns查询函数，新函数在每次连接或者重连时会调用，可自定dns缓存策略以及更新ip策略

**Comment by fawdlstty** [comment]
<http://libfv.fawdlstty.com/zh_hans/0_Startup.html#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE%E8%AE%BE%E7%BD%AE>
