### ISSUE TITLE
websocket 连接失败

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#35]
reconnect函数没有补获exception，认为是http方式连上了websocket服务器
接着发送login字符串，收到http 400 bad request错误。websocket服务器这个阶段还是以http方式处理请求，显然没有upgrade成websocket方式
请检查connectWS（）部分，特别是upgrade那段有没有问题.

---------------------以下在线测试可以接收数据-------------------------------------------------
websocket在线测试：http://coolaf.com/tool/chattest
wss服务器地址：wss://ws.bitget.com/mix/v1/stream  
发送订阅数据：{"op":"subscribe","args":[{"instType":"mc","channel":"books15","instId":"APEUSDT"}]}

**Comment by sudavida** [comment]
while (true) {
                try {
                       
                          auto[_data, _type] = co_await
                          wsConn->Recv();
                          co_await message_handle(_data);
                          auto _now = std::chrono::steady_clock::now();
                          if (string(_data) != "") {
                              LastMessageTime = _now;
                          } else
                              LOG_DBG << "ws received nothing...";
 
                } catch (std::exception &e) {
                    string ex = e.what();
                    LOG_ERR << "websocket:" << e.what();
                    while (!wsConn->IsConnect() || ex != "") {
                        co_await fv::Tasks::Delay(std::chrono::milliseconds(1));
                        LOG_INF << "websocket reconnecting...";
                        try {
                            wsConn = co_await
                            fv::ConnectWS(ws_host());
                            co_await open_handle();
                            ex = "";
                        } catch (...) {
                        }
                    }

                }
            }

**Comment by sudavida** [comment]
demo: 
 wsConn = co_await fv::ConnectWS("wss://ws.bitget.com/mix/v1/stream");
  if(wsConn->IsConnect()) {      
       std::string msg ="ping";   
       co_await wsConn->SendText(msg.data(), msg.size());  
 } else 
       std::cout<<"websocket connect error...\n";

**Comment by sudavida** [comment]
std::shared_ptr<fv::WsConn>                             wsConn = nullptr;

**Comment by fawdlstty** [comment]
请提供复现最小完整demo代码

**Comment by shoushouzhuo** [comment]
同样不会连接wss://ws.bitget.com/mix/v1/stream, 请求demo

**Comment by shoushouzhuo** [comment]
#ifdef _MSC_VER
# define _WIN32_WINNT 0x0601
# pragma warning (disable: 4068)
# pragma comment (lib, "Crypt32.lib")
# ifdef _RESUMABLE_FUNCTIONS_SUPPORTED
# 	undef _RESUMABLE_FUNCTIONS_SUPPORTED
# endif
# ifndef __cpp_lib_coroutine
# 	define __cpp_lib_coroutine
# endif
#endif

#include <iostream>
#include <string>
#include <fv/fv.h>


Task<void> test_client() {
    try {
        std::shared_ptr<fv::WsConn> wsConn = co_await fv::ConnectWS("wss://ws.bitget.com/mix/v1/stream");
        if (wsConn->IsConnect()) {
            std::string msg = R"({"op":"subscribe","args":[{"instType":"mc","channel":"books15","instId":"APEUSDT"}]})";
            co_await wsConn->SendText(msg.data(), msg.size());
            for (;;) {
                auto [_data, _type] = co_await wsConn->Recv();
                std::cout << _data << std::endl;
            }
        } else
            std::cout << "websocket connect error...\n";
    } catch (std::exception &_e) {
        std::cout << "catch exception: " << _e.what() << std::endl;
    } catch (...) {
        std::cout << "catch exception" << std::endl;
    }
    fv::Tasks::Stop();
}

int main() {
    fv::Tasks::Init();
    fv::Tasks::RunAsync(test_client);
    fv::Tasks::Run();
    return 0;
}
// 我用这demo不能连接失败, 请问楼主是怎么解决的呢

**Comment by fawdlstty** [comment]
@shoushouzhuo 测了一下你这个非bug，wss服务器本身就没法链接。你可以找其他ws客户端，如果能连，且libfv连不了，那就说明是libfv的问题，这种问题我才能修

**Comment by shoushouzhuo** [comment]
那还有个问题, 只要运行时间长一点就会遇到, 请求回来的数据有问题, 而beast框架就不会
![image](https://github.com/fawdlstty/libfv/assets/46802882/bb559386-e41f-455d-aeb8-819b4fa7ef3b)

**Comment by shoushouzhuo** [comment]
`using namespace std;
using namespace nlohmann;

Task<void> test_client() {
    try {
        std::shared_ptr<fv::WsConn> wsConn = co_await fv::ConnectWS("wss://fstream.binance.com:443/ws", fv::timeout(std::chrono::seconds(10)));
        if (wsConn->IsConnect()) {
            std::string msg = fmt::format(R"({{"method": "SUBSCRIBE","params":{},"id": 1}})", R"(["btcusdt@bookTicker","ethusdt@bookTicker"
, "bnbusdt@bookTicker", "arbusdt@bookTicker", "dydxusdt@bookTicker", "apeusdt@bookTicker","mkrusdt@bookTicker", "stxusdt@bookTicker"
, "highusdt@bookTicker", "linkusdt@bookTicker", "ssvusdt@bookTicker","uniusdt@bookTicker", "rndrusdt@bookTicker", "opusdt@bookTicker"])");
            co_await wsConn->SendText(msg.data(), msg.size());
            for (;;) {
//                std::this_thread::sleep_for(std::chrono::milliseconds(500));
                auto [_data, _type] = co_await wsConn->Recv();
//                cout << _data << endl;
                if (_type == fv::WsType::Text) {
                    try {
                        auto book_json = json::parse(_data);
                    } catch (exception &e) {
                        cout << "error 1 !!!" << endl;
                        std::cout << _data << std::endl;
                        continue;
                    }
                } else {
                    cout << "error 2222 !!!" << endl;
                    std::cout << _data << std::endl;
                }
            }
        } else
            std::cout << "websocket connect error...\n";
    } catch (std::exception &_e) {
        std::cout << "catch exception: " << _e.what() << std::endl;
    } catch (...) {
        std::cout << "catch exception" << std::endl;
    }
    fv::Tasks::Stop();
}

int main() {
    fv::Tasks::Init();
    fv::Tasks::RunAsync(test_client);
    fv::Tasks::Run();
    return 0;
}`

**Comment by fawdlstty** [comment]
@shoushouzhuo 未复现，请提供更详细的数据，实际接收内容是什么，以及libfv什么地方解析出错
