### ISSUE TITLE
Request::GetFromConn 函数没有解析get 参数

### ISSUE THREAD

**Issue by EFTNice** [fawdlstty/libfv#36]
QueryItems
ContentItems
这两个结构体变量没有引用 
例如get http://127.0.0.1:81/index.php?abc=1&&cc=23
不会解析出 abs 和cc 参数 而且 UrlPath 会包含这两个参数作为路径

**Comment by fawdlstty** [comment]
没看懂。能否给出示例代码，并给出错误的运行结果，以及期望的结果？

**Comment by EFTNice** [comment]
http://127.0.0.1:81/index.php?abc=1&&cc=23

没有解析 abc=1&&cc=23 这两个参数

**Comment by fawdlstty** [comment]
给出完整复现代码呗？以确认不是调用代码的问题；另外上图url是错的，没有两个&&相连的写法
