### ISSUE TITLE
Sec-WebSocket-Key 并不完备

### ISSUE THREAD

**Issue by BoneTM** [fawdlstty/libfv#38]
System.Net.WebSockets 中 IsWebSocketRequest 永远为 false 经调试 Sec-WebSocket-Key 不通过验证
手动设置 Key 后连接正常，之前有人的 issue 提出无法连接可能也是此问题

![QQ截图20230923164447](https://github.com/fawdlstty/libfv/assets/48622532/e763e792-502c-47ad-9a87-14b50bd9e135)
![QQ截图20230923164501](https://github.com/fawdlstty/libfv/assets/48622532/fe801e03-cc8c-476f-b8bd-2dc1297dcea1)
![QQ截图20230923164517](https://github.com/fawdlstty/libfv/assets/48622532/66abcb4a-3735-4ce0-9ee7-3287bf9fd8a5)

**Comment by BoneTM** [comment]
random_str改为16也可正常运作

**Comment by fawdlstty** [comment]
奇怪，我测试改为16也不行。看了下应该是16的。我先改这个吧
