### ISSUE TITLE
websocket demo: end of file报错。。

### ISSUE THREAD

**Issue by shoushouzhuo2** [fawdlstty/libfv#40]
![微信截图_20231026173457](https://github.com/fawdlstty/libfv/assets/148861172/79830849-c842-4c6f-9607-85377d57ed33)
[main_test5.txt](https://github.com/fawdlstty/libfv/files/13175675/main_test5.txt)

**Comment by fawdlstty** [comment]
end of file可能是服务器端关闭连接了，如果没有数据接收不全，那很可能是正常现象。看截图应该是对的

**Comment by fawdlstty** [comment]
你得确认一下服务器端关闭链接的机制，有的是一段时间没通讯就关；有的是必须得发心跳包，不发就关；有的是发送完一些数据就关

**Comment by shoushouzhuo2** [comment]
> 你得确认一下服务器端关闭链接的机制，有的是一段时间没通讯就关；有的是必须得发心跳包，不发就关；有的是发送完一些数据就关
![image](https://github.com/fawdlstty/libfv/assets/148861172/d5a8dee2-ea9f-4c92-8979-5d7b771ce8f6)
我看了心跳机制，而且也在源码里打印了， 心跳这块应该不需要做特别处理吧， 我看您源码里pong回复也没有问题呀

**Comment by fawdlstty** [comment]
所以你得确认服务器端到底是怎样的连接维持的机制，，，不是看客户端
