### ISSUE TITLE
conn断掉重连连接不上，重新启动程序，可连

### ISSUE THREAD

**Issue by sudavida** [fawdlstty/libfv#6]
包括卡断的情况，也重连不上，是不是有其他原因，妨碍重连

**Comment by sudavida** [comment]
重连是需要加锁的，要不后面的请求不知道在连接，造成多次重连的情况

**Comment by sudavida** [comment]
加锁也不行，后面照常重复reconnect（），我加了连接状态

**Comment by fawdlstty** [comment]
http行不行

**Comment by sudavida** [comment]
如果重复reconnect（），会造成不断的连接， 关闭，再连接。所以要状态管理：CONNECTING，CONNECTED，CLOSED。。。

即使加了这些，还没有解决断线重连连不上的情况。
网络正常的。
服务器端呢，猜测由于访问频率过高被断掉，禁止访问？但是重启程序，这些都正常了。
现在在查重连的过程中，哪个地方有问题。

**Comment by fawdlstty** [comment]
所以，http行不行

**Comment by sudavida** [comment]
http就一直试着发数据呀，从http那开始连也不是不行的

**Comment by sudavida** [comment]
SSLSocket要重新初始化吗

**Comment by fawdlstty** [comment]
我是说，测试访问地址换成http。我遇到过ssl重连不上需要重启的情况，原因就是ssl版本太低。已更新支持外部配置ssl版本

**Comment by fawdlstty** [comment]
http://libfv.fawdlstty.com/zh_hans/0_Startup.html#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE%E8%AE%BE%E7%BD%AE

**Comment by sudavida** [comment]
我要访问的地址都是https连接的 ，这个tls方式可能中间会出错，我改成了：	//Ssl::context SslCtx { Ssl::context::tls };
    Ssl::context SslCtx { Ssl::context::context::sslv23 };//改

**Comment by sudavida** [comment]
for (size_t i = 0; i < 2; i++) {
                try {
                    Conn->Close();  //这里尝试断掉连接
                    // send
                    co_await Conn->Send (_data.data (), _data.size ());
                    break;
                } catch (...) {
                    //if (i == 1) throw;
                }
 
                co_await Conn->Reconnect ();
            }

**Comment by sudavida** [comment]
reconnect:18.167.61.173:443
reconnected...
reconnect->handshake:
terminate called after throwing an instance of 'std::system_error'
  what():  cancel: Bad file descriptor

**Comment by sudavida** [comment]
我尝试断掉连接，reconnect（），socket可以连接，但是握手失败，报错：错误的文件描述符。我理解上次的连接没清理干净

**Comment by sudavida** [comment]
Sslsocket 需要重置？

**Comment by sudavida** [comment]
reconnected...
reconnect->handshake:
reconnect->handshake1://握手成功
reconnect:1 //连接成功
cancel: //下面jasio函数 中报错
terminate called after throwing an instance of 'std::system_error'
  what():  cancel: Bad file descriptor

**Comment by sudavida** [comment]
reactive_socket_service_base.ipp line155左右，这个函数报错：

asio::error_code reactive_socket_service_base::cancel(
    reactive_socket_service_base::base_implementation_type& impl,
    asio::error_code& ec)
{
  if (!is_open(impl))
  {
    std::cout<<"cancel:"<<"\n";
    ec = asio::error::bad_descriptor;
    return ec;
  }

  ASIO_HANDLER_OPERATION((reactor_.context(),
        "socket", &impl, impl.socket_, "cancel"));

  reactor_.cancel_ops(impl.socket_, impl.reactor_data_);
  ec = asio::error_code();
  return ec;
}

**Comment by sudavida** [comment]
cancel()会取消当前socket上的所有异步操作。

或者理解成该套接字上的异步操作立即返回，然后调用各自的回调函数，并且给回调函数传递一个boost::asio::error::operation_aborted(作为字段boost::system::error_code的实参)

**Comment by sudavida** [comment]
这是自己主动断了重连，连接上了，但是这会引发cancel操作，报Bad file descriptor，也许已经连接的不是前面的IP了。

**Comment by sudavida** [comment]
reconnect to close socket, status:1
reconnect: closing socket.1
reconnect:16.163.66.66:443
connected...
reconnect->handshake1:
reconnect->handshake2:
first line:HTTP/1.1 200

**Comment by sudavida** [comment]
inline void SslConn::Close () {
    bool b = SslSocket.next_layer ().is_open ();
    std::cout<<"reconnect to close socket, status:"<< b<<"\n";
    if (SslSocket.next_layer ().is_open ()) {
        std::cout<<"reconnect: closing socket."<< b<<"\n";
        SslSocket.next_layer ().close ();
        //SslSocket.next_layer ().shutdown (SocketBase::shutdown_both);
    }
}

**Comment by sudavida** [comment]
去掉shutdown，就可以了，奇怪。重连是不同的IP，确实已经重连成功了

**Comment by sudavida** [comment]
改成这样，可以：
inline void SslConn::Close () {
    if (SslSocket.next_layer ().is_open ()) {
        SslSocket.next_layer ().close ();
        try {
            SslSocket.next_layer ().shutdown (SocketBase::shutdown_both);
        }catch(...){
        }
    }
}

**Comment by fawdlstty** [comment]
close是关闭自身会话句柄，shutdown是发送tcp挥手数据包

**Comment by fawdlstty** [comment]
fixed
